[package]
name = "bookshelf2lefdef"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "bookshelf2lefdef"
path = "bin/bookshelf2lefdef.rs"


[dependencies]
anyhow = "1.0.98"
bytes = "1.10.1"
clap = { version = "4.5.42", features = ["derive"] }
tokio = { version = "1.47.1", features = ["full"] }
